orders/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.orders, name='orders'),
    path('basket_adding/', views.basket_adding, name='basket_adding'),
]

products/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.products, name='products'),
    path('product/<int:product_id>/', views.product, name='product')
]

sneaker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('mainpage.urls')),
    path('', include ('products.urls')),
    path('', include ('orders.urls')),

] \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models

class ProductCategory(models.Model):
    name=models.CharField(max_length=64,blank=True, null=True, default=None)
    is_active=models.BooleanField(default=True)

    def __str__(self):
        return "%s %s" % (self.id, self.name)

    class Meta:
        verbose_name='Категория товара'
        verbose_name_plural='Категория товаров'

class Product(models.Model):
    name=models.CharField('Наименование товара', max_length=120)
    short_description = models.TextField('Описание товара', blank=True, null=True, default=None)
    discount=models.IntegerField(default=0)
    category=models.ForeignKey(ProductCategory, blank=True, null=True, default=None, on_delete=models.CASCADE)
    description=models.TextField('Описание товара', blank=True, null=True, default=None)
    is_active = models.BooleanField('В наличии',default=True)
    price = models.DecimalField('Цена товара', max_digits=10, decimal_places=2, default=0)
    created=models.DateTimeField('Дата создания товара', auto_now_add=True, auto_now=False)
    updated=models.DateTimeField('Последние изменения', auto_now_add=True, auto_now=False)

    def __str__(self):
        return "№ товара:  (%s) Наименование товара:  //%s// Цена:*%s*" % (self.id,self.name, self.price)

    class Meta:
        verbose_name='Товар'
        verbose_name_plural='Товары'

class ProductImage(models.Model):
    product=models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product_images/')
    is_active=models.BooleanField(default=True)
    is_main = models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True, auto_now=False)
    updated=models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return "(%s) %s" % (self.id, self.product)

    class Meta:
        verbose_name='Фотография'
        verbose_name_plural='Фотографии к товарам (admin)'

products/views.py
from django.shortcuts import render
from .models import *


def products(request):
    product=Product.objects.all()
    return render(request, 'products/products_list.html', {'product':product})

def product(request, product_id):
    product=Product.objects.get(id=product_id)
    return render(request, 'products/product.html', {'product': product})

products/templates/products/product.html
{% extends 'mainpage/base.html' %}
{% load static %}

{% block content %}
    <div class="container" align="center">
        <div class="row">
            {% if product.discount > 0 %}
            <div class="col-lg-12" align="">
                {% for image_item in product.productimage_set.all %}
                <div class="discount_container">-{{ product.discount }}%</div>
                <img src="{{ image_item.image.url }}" class="img-responsive" height="500px" width="px">
                {% endfor %}
                {% endif %}
                <div class="col-lg-6">
                    <h1 class="text-center">
                        {{ product.name }}

                    </h1>
                    <div class="">
                        <p>
                            Цена: {{ product.price }} руб.
                            {% if product.is_active == True %}
                            В наличии
                            {% else %}
                            Нет в наличии
                            {% endif %}
                        </p>
                    </div>
                    <div>
                    <div class="">
                        {{ product.description }}
                    </div>
                        <br />
                        <p>Колличество</p>
                        <form id="form_buying_product" class="form-check form-check-inline" action="{% url 'basket_adding' %}">
                            {% csrf_token %}
                            <input type="number" class="form-control" name="number" id="number">
                        <button type="submit" id="submit_btn" class="btn btn-success bnt-buy"
                            data-product_id = "{{ product.id }}"
                            data-name = "{{ product.name }}"
                            data-price = "{{ product.price }}"
                        >
                            Купить
                        </button>
                        </form>

                </div>
            </div>
        </div>
    </div>

{% endblock %}